services:
  modreplybot:
    image: ghcr.io/imonlytryingtohelp/modreplybot:latest
    container_name: modreplybot
    env_file:
      - .env
    volumes:
      - ./docker/config:/app/config
      - ./docker/DB:/app/DB
    restart: unless-stopped
  web:
    image: ghcr.io/imonlytryingtohelp/modreplybot:latest
    command: ["python", "web/server.py"]
    container_name: modreplybot-web
    ports:
      - "5289:8080"
    volumes:
      - ./docker/DB:/app/DB
    restart: unless-stopped